name: mini_game_
description: "A Flutter mini games collection app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  google_mobile_ads: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/sounds/
    - assets/sounds/snake/
    - assets/sounds/space_shooter/
    - assets/music/
    - assets/flags/
  
  # For localization
  # generate: true
